const Icon = {
  egg: require('./image/egg.jpeg'),
  yakisoba: require('./image/yakisoba.jpeg'),
  pasta: require('./image/pasta.jpeg'),
  clear: require('./image/cross-small.png'),
  back: require('./image/angle-left.png'),
  collecting: require('./image/rick.jpeg'),
  clock: require('./image/clock.png'),
  share: require('./image/share.png'),
  circle: require('./image/circumference.png'),
  pen: require('./image/pen.png'),
};

const data = [
  {
    image: Icon.egg,
    name: 'Egg',
    description:
      "Description about Offer, It's basic terms, access limits, location, availability, time and price ranges.",
    author: '@John',
    price: '$10',
    miles: '10',
    days: '30',
    category: 'Food',
    value: 10,
    collectingAmount: 23,
    amountLeft: 4,
    shares: 425,
    paymentType: 'Full/Installments',
    validity: '14 Mar,23 - 27 Mar,23',
  },
  {
    image: Icon.yakisoba,
    name: 'Yakisoba',
    description:
      "Description about Offer, It's basic terms, access limits, location, availability, time and price ranges.",
    author: '@Tom',
    price: '$100',
    miles: '20',
    days: '30',
    category: 'Food',
    value: 100,
    collectingAmount: 23,
    amountLeft: 4,
    shares: 425,
    paymentType: 'Full/Installments',
    validity: '14 Mar,23 - 27 Mar,23',
  },
  {
    image: Icon.pasta,
    name: 'Pasta',
    description:
      "Description about Offer, It's basic terms, access limits, location, availability, time and price ranges.",
    author: '@Tom',
    price: '$50',
    miles: '50',
    days: '30',
    category: 'Food',
    value: 50,
    collectingAmount: 23,
    amountLeft: 4,
    shares: 425,
    paymentType: 'Full/Installments',
    validity: '14 Mar,23 - 27 Mar,23',
  },
  {
    image: Icon.pasta,
    name: 'Tea',
    description:
      "Description about Offer, It's basic terms, access limits, location, availability, time and price ranges.",
    author: '@Tom',
    price: '$333',
    miles: '60',
    days: '30',
    category: 'Drinks',
    value: 333,
    collectingAmount: 23,
    amountLeft: 4,
    shares: 425,
    paymentType: 'Full/Installments',
    validity: '14 Mar,23 - 27 Mar,23',
  },
  {
    image: Icon.pasta,
    name: 'Tennis',
    description:
      "Description about Offer, It's basic terms, access limits, location, availability, time and price ranges.",
    author: '@Tom',
    price: '$333',
    miles: '60',
    days: '30',
    category: 'Sports',
    value: 333,
    collectingAmount: 23,
    amountLeft: 4,
    shares: 425,
    paymentType: 'Full/Installments',
    validity: '14 Mar,23 - 27 Mar,23',
  },
  {
    image: Icon.pasta,
    name: 'Juice',
    description:
      "Description about Offer, It's basic terms, access limits, location, availability, time and price ranges.",
    author: '@Alan',
    price: '$333',
    miles: '60',
    days: '30',
    category: 'Drinks',
    value: 333,
    collectingAmount: 23,
    amountLeft: 4,
    shares: 425,
    paymentType: 'Full/Installments',
    validity: '14 Mar,23 - 27 Mar,23',
  },
  {
    image: Icon.pasta,
    name: 'Football',
    description:
      "Description about Offer, It's basic terms, access limits, location, availability, time and price ranges.",
    author: '@Tom',
    price: '$333',
    miles: '60',
    days: '30',
    category: 'Sports',
    value: 290,
    collectingAmount: 23,
    amountLeft: 4,
    shares: 425,
    paymentType: 'Full/Installments',
    validity: '14 Mar,23 - 27 Mar,23',
  },
  {
    image: Icon.pasta,
    name: 'Card',
    description:
      "Description about Offer, It's basic terms, access limits, location, availability, time and price ranges.",
    author: '@Tim',
    price: '$333',
    miles: '60',
    days: '30',
    category: 'Game',
  },
  {
    image: Icon.pasta,
    name: 'Chess',
    description:
      "Description about Offer, It's basic terms, access limits, location, availability, time and price ranges.",
    author: '@Alan',
    price: '$333',
    miles: '60',
    days: '30',
    category: 'Game',
    value: 290,
    collectingAmount: 23,
    amountLeft: 4,
    shares: 425,
    paymentType: 'Full/Installments',
    validity: '14 Mar,23 - 27 Mar,23',
  },
  {
    image: Icon.pasta,
    name: 'Swimming',
    description:
      "Description about Offer, It's basic terms, access limits, location, availability, time and price ranges.",
    author: '@John',
    price: '$333',
    miles: '60',
    days: '30',
    category: 'Sports',
    value: 290,
    collectingAmount: 23,
    amountLeft: 4,
    shares: 425,
    paymentType: 'Full/Installments',
    validity: '14 Mar,23 - 27 Mar,23',
  },
];

export {Icon, data};
